url: http://www.baidu.com
log:
  file_name: test.log
  backup: 5
  console_level: WARNING
  file_level: DEBUG
  pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
wangzhe: https://pvp.qq.com/web201605/herolist.shtml
new_pifu: https://pvp.qq.com/web201605/wallpaper.shtml###